/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg44_gui07;

/**
 *
 * @author Gerardo
 */
import javax.swing.JOptionPane;
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        tieneConyuge = new javax.swing.JCheckBox();
        letreroNombreConyuge = new javax.swing.JLabel();
        nombreConyuge = new javax.swing.JTextField();
        letreroEdadConyuge = new javax.swing.JLabel();
        edadConyuge = new javax.swing.JTextField();
        botonProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("20012002049");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nombre:");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Edad:");

        edad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Salario:");

        salario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        tieneConyuge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tieneConyuge.setText("Tiene conyuge");
        tieneConyuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieneConyugeActionPerformed(evt);
            }
        });

        letreroNombreConyuge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        letreroNombreConyuge.setText("Nombre:");

        nombreConyuge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        letreroEdadConyuge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        letreroEdadConyuge.setText("Edad:");

        edadConyuge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        botonProcesar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonProcesar.setText("PROCESAR");
        botonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tieneConyuge)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letreroNombreConyuge)
                            .addComponent(letreroEdadConyuge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreConyuge)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edadConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(botonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tieneConyuge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letreroNombreConyuge)
                    .addComponent(nombreConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letreroEdadConyuge)
                    .addComponent(edadConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tieneConyugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieneConyugeActionPerformed
        //el siguiente codigo puede optimizarse:
        if( tieneConyuge.isSelected() == true )
        {
            letreroNombreConyuge.setVisible(true);
            letreroEdadConyuge.setVisible(true);
            nombreConyuge.setVisible(true);
            edadConyuge.setVisible(true);
        }
        else{
            letreroNombreConyuge.setVisible(false);
            letreroEdadConyuge.setVisible(false);
            nombreConyuge.setVisible(false);
            edadConyuge.setVisible(false);
        }
    }//GEN-LAST:event_tieneConyugeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //simular validacion del checkbox
        tieneConyugeActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void botonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesarActionPerformed
        //validaciones
        try{
            if( nombre.getText().length() == 0 ){
                JOptionPane.showMessageDialog(this, "Nombre es obligatorio");
                return; //terminar la funcion del evento (no sigue para abajo)
            }
            if( edad.getText().length() == 0 ){
                JOptionPane.showMessageDialog(this, "Edad es obligatoria");
                return;
            }
            if( Integer.parseInt(edad.getText()) < 18 ){
                JOptionPane.showMessageDialog(this, "Edad debe ser >= 18");
                return;
            }
            if( salario.getText().length() == 0 ){
                JOptionPane.showMessageDialog(this, "Salario es obligatorio");
                return;
            }
            if( Double.parseDouble(salario.getText()) < 0 ){
                JOptionPane.showMessageDialog(this, "Salario debe de ser >= 0");
                return;
            }
            //si tiene conyuge debe validar nombre y edad del conyuge
            if( tieneConyuge.isSelected() == true ){
                if( nombreConyuge.getText().length() == 0 ){
                    JOptionPane.showMessageDialog(this, "Nombre del conyuge es obligatorio");
                    return; //terminar la funcion del evento (no sigue para abajo)
                }
                if( edadConyuge.getText().length() == 0 ){
                    JOptionPane.showMessageDialog(this, "Edad del conyuge es obligatoria");
                    return;
                }
                if( Integer.parseInt(edadConyuge.getText()) < 18 ){
                    JOptionPane.showMessageDialog(this, "Edad del conyuge debe ser >= 18");
                    return;
                }
            }
            
            //si llego aqui todo salio bien
            JOptionPane.showMessageDialog(this, "Formulario procesado con exito.");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Revise los datos.");
        }
    }//GEN-LAST:event_botonProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonProcesar;
    private javax.swing.JTextField edad;
    private javax.swing.JTextField edadConyuge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel letreroEdadConyuge;
    private javax.swing.JLabel letreroNombreConyuge;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreConyuge;
    private javax.swing.JTextField salario;
    private javax.swing.JCheckBox tieneConyuge;
    // End of variables declaration//GEN-END:variables
}
