/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg39_gui02;

/**
 *
 * @author Gerardo
 */
import javax.swing.JOptionPane; //clase para mostrar alertas
import java.util.Calendar;
import java.text.SimpleDateFormat;
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloUNAH = new javax.swing.JLabel();
        botonAlerta = new javax.swing.JButton();
        caja1 = new javax.swing.JTextField();
        botonCambioTitulo = new javax.swing.JButton();
        botonFechaHora = new javax.swing.JButton();
        labelFechaHora = new javax.swing.JLabel();
        btnHabilitar = new javax.swing.JButton();
        btnDeshabilitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("20012002049 - Gerardo");
        setBackground(new java.awt.Color(204, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tituloUNAH.setBackground(new java.awt.Color(255, 204, 153));
        tituloUNAH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloUNAH.setForeground(new java.awt.Color(255, 0, 0));
        tituloUNAH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloUNAH.setText("UNAH 2024");
        tituloUNAH.setToolTipText("Este es el titulo");
        tituloUNAH.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 204, 255)));
        tituloUNAH.setOpaque(true);

        botonAlerta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonAlerta.setText("Haga click aqui");
        botonAlerta.setToolTipText("presione este boton");
        botonAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlertaActionPerformed(evt);
            }
        });

        caja1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        caja1.setForeground(new java.awt.Color(204, 0, 51));
        caja1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        caja1.setText("algo");

        botonCambioTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCambioTitulo.setText("Cambiar el Titulo de la ventana");
        botonCambioTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambioTituloActionPerformed(evt);
            }
        });

        botonFechaHora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonFechaHora.setText("Ver Fecha/Hora");
        botonFechaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFechaHoraActionPerformed(evt);
            }
        });

        labelFechaHora.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelFechaHora.setText("jLabel1");

        btnHabilitar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHabilitar.setText("Habilitar la caja de texto");
        btnHabilitar.setToolTipText("");
        btnHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitarActionPerformed(evt);
            }
        });

        btnDeshabilitar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeshabilitar.setText("Deshabilitar la caja de texto");
        btnDeshabilitar.setToolTipText("");
        btnDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(tituloUNAH, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(botonAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(labelFechaHora)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(botonCambioTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeshabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(btnHabilitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloUNAH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnHabilitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeshabilitar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(botonCambioTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFechaHora))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //codigo que se ejecuta al mostrar este JFrame en ptanlla
        //en este caso vamos a forzar la aplicacion del color de fondo
        //que elegimos
        this.getContentPane().setBackground( this.getBackground() );
    }//GEN-LAST:event_formWindowOpened

    private void botonAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlertaActionPerformed
        //mostrar una alerta en pantalla
        //hay que importar a javax.swing.JOptionPane
        JOptionPane.showMessageDialog(this, "Hola Estudiantes de Sistemas");
        //cambiamos el contenido del JLabel llamado tituloUNAH
        tituloUNAH.setText("PUMAS UNAH");
    }//GEN-LAST:event_botonAlertaActionPerformed

    private void botonCambioTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambioTituloActionPerformed
        this.setTitle("Este es el nuevo titulo de la ventana");
    }//GEN-LAST:event_botonCambioTituloActionPerformed

    private void botonFechaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFechaHoraActionPerformed
        //para usar fecha usamos la clase java.util.Calendar
        //para darle formato a la fecha/hora usamos java.text.SimpleDateFormat
        //crear un objeto Calendar
        Calendar f1 = Calendar.getInstance();
        //f1.set(2024, 6, 30, 17, 45, 23); esto es una fecha/hora fija (no cambia)
        //lo anterior crea un objeto Calendar con la fecha/hora de la computadora
        //mostrar dicha fecha en labelFechaHora
        //pero antes hay que aplicar formato de fecha y hora
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/YYYY hh:mm:ss a");
        labelFechaHora.setText( formateador.format( f1.getTime() ) );
    }//GEN-LAST:event_botonFechaHoraActionPerformed

    private void btnDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshabilitarActionPerformed
        //setEditable en false impide escribir en la caja;
        //pero permite seleccionar el texto
        caja1.setEditable(false);
        
        //setEnabled en false impide hacer click en la caja de texto
        //caja1.setEnabled(false);
        
        //setVisible en false oculta la caja
        //caja1.setVisible(false);
        
        //elija Usted cual de los tres le sirve
    }//GEN-LAST:event_btnDeshabilitarActionPerformed

    private void btnHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitarActionPerformed
        //aqui haga lo inverso que hizo en deshabilitar
        caja1.setEditable(true);
        //caja1.setEnabled(true);
        //caja1.setVisible(true);
        //elija Usted cual de los tres le sirve
    }//GEN-LAST:event_btnHabilitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlerta;
    private javax.swing.JButton botonCambioTitulo;
    private javax.swing.JButton botonFechaHora;
    private javax.swing.JButton btnDeshabilitar;
    private javax.swing.JButton btnHabilitar;
    private javax.swing.JTextField caja1;
    private javax.swing.JLabel labelFechaHora;
    private javax.swing.JLabel tituloUNAH;
    // End of variables declaration//GEN-END:variables
}
