/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg45_gui08;

import java.awt.Color;

/**
 *
 * @author Gerardo Portillo
 */
import javax.swing.JOptionPane;
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colores = new javax.swing.ButtonGroup();
        refrescos = new javax.swing.ButtonGroup();
        rojo = new javax.swing.JRadioButton();
        amarillo = new javax.swing.JRadioButton();
        azul = new javax.swing.JRadioButton();
        cocaCola = new javax.swing.JRadioButton();
        pepsi = new javax.swing.JRadioButton();
        botonProcesar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("20012002049");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        colores.add(rojo);
        rojo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rojo.setText("Rojo");
        rojo.setOpaque(false);
        rojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rojoStateChanged(evt);
            }
        });

        colores.add(amarillo);
        amarillo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        amarillo.setSelected(true);
        amarillo.setText("Amarillo");
        amarillo.setOpaque(false);
        amarillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                amarilloStateChanged(evt);
            }
        });

        colores.add(azul);
        azul.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        azul.setText("Azul");
        azul.setOpaque(false);
        azul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                azulStateChanged(evt);
            }
        });

        refrescos.add(cocaCola);
        cocaCola.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cocaCola.setText("Coca Cola");
        cocaCola.setOpaque(false);

        refrescos.add(pepsi);
        pepsi.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pepsi.setText("Pepsi");
        pepsi.setOpaque(false);

        botonProcesar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        botonProcesar.setText("PROCESAR");
        botonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProcesarActionPerformed(evt);
            }
        });

        botonLimpiar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rojo)
                        .addGap(28, 28, 28)
                        .addComponent(amarillo)
                        .addGap(18, 18, 18)
                        .addComponent(azul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(cocaCola)
                        .addGap(18, 18, 18)
                        .addComponent(pepsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(botonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rojo)
                    .addComponent(amarillo)
                    .addComponent(azul))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cocaCola)
                    .addComponent(pepsi))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rojoStateChanged
        //evento de cambio de estado del radioButton
        if( rojo.isSelected() == true )
            this.getContentPane().setBackground(Color.RED);
        if( amarillo.isSelected() == true )
            this.getContentPane().setBackground(Color.YELLOW);
        if( azul.isSelected() == true )
            this.getContentPane().setBackground(Color.BLUE);
    }//GEN-LAST:event_rojoStateChanged

    private void amarilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_amarilloStateChanged
        rojoStateChanged(null);
    }//GEN-LAST:event_amarilloStateChanged

    private void azulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_azulStateChanged
        rojoStateChanged(null);
    }//GEN-LAST:event_azulStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //evento al presentar el jframe en pantalla
        rojoStateChanged(null);
    }//GEN-LAST:event_formWindowOpened

    private void botonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProcesarActionPerformed
        //si no hay bebida seleccionada no sigue:
        if( cocaCola.isSelected() == false && pepsi.isSelected() == false ){
            JOptionPane.showMessageDialog(this, "Seleccione una bebida");
            return; //no continuar con este evento
        }
        if( cocaCola.isSelected() == true )
            JOptionPane.showMessageDialog(this, "Ha seleccionado Coca Cola");
        if( pepsi.isSelected() == true )
            JOptionPane.showMessageDialog(this, "Ha seleccionado Pepsi");
    }//GEN-LAST:event_botonProcesarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        //este boton va a dejar los radioButton de los grupos desactivados
        colores.clearSelection();
        refrescos.clearSelection();
        //remover el fondo
        this.getContentPane().setBackground(null);
    }//GEN-LAST:event_botonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton amarillo;
    private javax.swing.JRadioButton azul;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonProcesar;
    private javax.swing.JRadioButton cocaCola;
    private javax.swing.ButtonGroup colores;
    private javax.swing.JRadioButton pepsi;
    private javax.swing.ButtonGroup refrescos;
    private javax.swing.JRadioButton rojo;
    // End of variables declaration//GEN-END:variables
}
